@startuml
' !include D:\plantuml\style_c4\core.puml
!include /Users/zhangjunqing/plantuml/style_c4/core.puml

namespace app.home #FDF6E3{
  class HomeDlg {
    btnPet: Box
    onBtnPetClick()
  }

  class PetSpineBox {
    status: enum
    playActions()
    onPetBoxClick()
  }

  class PetSelectDlg {
    boxSelectPet: Box
    onBtnSlectClick()
  }

  HomeDlg *-- PetSelectDlg
  HomeDlg *-- PetSpineBox
}


namespace app.pet #E4FAD5{
  class PetDlg {
    imgBg: Image
    tips: Box
    petLvl: PetLvlRewardView
    petNode: PetNode
    petFeedView: PetFeedView
    harvestCoins()
  }

  class PetLvlRewardView {
    progressLvl: ProgressBar
    lblPetLvl: Label
    lblPetExp: Label
    imgReward: Image
    luckyBag: Box
    tipsLvl: Box
    tipsLuck: Box
    updateData()
    private playLuckyBagAni()
  }

  class PetNode {
    spineNode: Spine
    imgIntimacy: Image
    boxIntimacy: Box
    status: enum
    updateData()
    private playStats()
    private playActions()
  }

  class PetFeedView {
    btnFood: Box
    btnWater: Box
    updateData()
    onBtnFoodClick()
    onBtnWaterClick()
  }

  PetDlg *-- PetLvlRewardView
  PetDlg *-- PetNode
  PetDlg *-- PetFeedView

}

app.home.PetSpineBox .. app.pet.PetDlg


@enduml